name: Deploy to S3
on: [push]
jobs: 
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: yarn test
    - run: yarn build
    - name: Configure AWS creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Deploy code to S3
      run: |
        aws s3 sync build/ s3://${{ secrets.S3_BUCKET_NAME }}